apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
#  automountServiceAccountToken: false
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: [ "--context=git://github.com/heipparallaa22/kaninkolo-testi",
              "--context-sub-path=kaniko-standalone-setup/restapi/docker/",
              "--dockerfile=Dockerfile",
              "--destination=qwerty22/restapi:3.1" ]
      volumeMounts:
        - name: kaniko-secret
          mountPath: "/kaniko/.docker"
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
          - key: .dockerconfigjson
            path: config.json
