apiVersion: v1
kind: Service
metadata:
  name: wiremock
spec:
  type: NodePort
  selector:
    app: wiremock
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 9090
      targetPort: 9090
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30090