apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
#  automountServiceAccountToken: false
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: [ "--context=git://github.com/heipparallaa22/kaninkolo-testi",
              "--dockerfile=spring-jar-image/dockerfile/Dockerfile",
              "--context-sub-path=spring-jar-image/dockerfile/",
              "--destination=qwerty22/restapi:2.0" ]
      volumeMounts:
        - name: kaniko-secret
          mountPath: "/kaniko/.docker"
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
          - key: .dockerconfigjson
            path: config.json
